name: validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt-validate:
    name: fmt + validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [simple, production]
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: terraform fmt (root + modules + examples)
        run: terraform fmt -check -recursive

      - name: terraform init (no backend)
        working-directory: examples/${{ matrix.example }}
        run: terraform init -backend=false

      - name: terraform validate
        working-directory: examples/${{ matrix.example }}
        run: terraform validate

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: true  # report but don't block
